// Software
const SOFTWARE = [
  { nome: "Adobe Photoshop 1 Mês", preco: 54.90, emoji: "🎨", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_e5iveqe5iveqe5iv.png?auto=format&fit=crop&w=400&q=80", descricao: "Editor de imagens profissional.", categoria: "Software", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "Adobe Creative Cloud 1 Mês", preco: 79.90, emoji: "🎨", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_q8e4l0q8e4l0q8e4.png?auto=format&fit=crop&w=400&q=80", descricao: "Suite completa Adobe.", categoria: "Software", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "Microsoft Office 365 1 Ano", preco: 199.90, emoji: "📄", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_hjlyachjlyachjly.png?auto=format&fit=crop&w=400&q=80", descricao: "Office completo por 1 ano.", categoria: "Software", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "AutoCAD 1 Mês", preco: 149.90, emoji: "🏗️", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_6abzr16abzr16abz.png?auto=format&fit=crop&w=400&q=80", descricao: "Software de design profissional.", categoria: "Software", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "Corel Draw 2024", preco: 399.90, emoji: "🎨", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_7ltzip7ltzip7ltz.png?auto=format&fit=crop&w=400&q=80", descricao: "Suite de design gráfico.", categoria: "Software", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "Final Cut Pro", preco: 299.90, emoji: "🎬", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_c6ph00c6ph00c6ph.png?auto=format&fit=crop&w=400&q=80", descricao: "Edição de vídeo profissional.", categoria: "Software", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
];

// E-BOOKS
const EBOOKS = [
  { nome: "E-book: Programação em Python", preco: 39.90, emoji: "📖", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_5pprhl5pprhl5ppr.png?auto=format&fit=crop&w=400&q=80", descricao: "Guia completo de Python.", categoria: "E-Books", status: "disponivel", pagamento: ["pix"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "E-book: Web Design Moderno", preco: 49.90, emoji: "🎨", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_xeyrwgxeyrwgxeyr.png?auto=format&fit=crop&w=400&q=80", descricao: "Design responsivo e atual.", categoria: "E-Books", status: "disponivel", pagamento: ["pix"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "E-book: Marketing Digital", preco: 59.90, emoji: "📱", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_rxzce1rxzce1rxzc.png?auto=format&fit=crop&w=400&q=80", descricao: "Estratégias de marketing online.", categoria: "E-Books", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "E-book: SEO Avançado", preco: 44.90, emoji: "🔍", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_d9bhfpd9bhfpd9bh.png?auto=format&fit=crop&w=400&q=80", descricao: "Otimização para buscas.", categoria: "E-Books", status: "disponivel", pagamento: ["pix"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "E-book: JavaScript Completo", preco: 54.90, emoji: "💻", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_i3on6ii3on6ii3on.png?auto=format&fit=crop&w=400&q=80", descricao: "Da introdução ao avançado.", categoria: "E-Books", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "E-book: React.js Prático", preco: 64.90, emoji: "⚛️", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_is37wlis37wlis37.png?auto=format&fit=crop&w=400&q=80", descricao: "Desenvolvimento com React.", categoria: "E-Books", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "E-book: Empreendedorismo Digital", preco: 69.90, emoji: "💼", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_cg6dg1cg6dg1cg6d.png?auto=format&fit=crop&w=400&q=80", descricao: "Comece seu negócio online.", categoria: "E-Books", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "E-book: Gestão de Projetos Ágeis", preco: 74.90, emoji: "📊", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_r1yrdzr1yrdzr1yr.png?auto=format&fit=crop&w=400&q=80", descricao: "Metodologias Agile e Scrum.", categoria: "E-Books", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
];

// CURSOS
const CURSOS = [
  { nome: "Curso: Desenvolvimento Web Completo", preco: 149.90, emoji: "💻", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_5u7g2h5u7g2h5u7g.png?auto=format&fit=crop&w=400&q=80", descricao: "HTML, CSS, JavaScript e mais.", categoria: "Cursos", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "Curso: Data Science com Python", preco: 199.90, emoji: "📊", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_lmwwvzlmwwvzlmww.png?auto=format&fit=crop&w=400&q=80", descricao: "Análise de dados profissional.", categoria: "Cursos", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "Curso: Machine Learning", preco: 249.90, emoji: "🤖", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_74tzxo74tzxo74tz.png?auto=format&fit=crop&w=400&q=80", descricao: "IA e algoritmos de ML.", categoria: "Cursos", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "Curso: Fotografia Profissional", preco: 179.90, emoji: "📸", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_qqfjxgqqfjxgqqfj.png?auto=format&fit=crop&w=400&q=80", descricao: "Do básico ao avançado.", categoria: "Cursos", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "Curso: Edição de Vídeo com After Effects", preco: 189.90, emoji: "🎬", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_73sm5b73sm5b73sm.png?auto=format&fit=crop&w=400&q=80", descricao: "Efeitos visuais profissionais.", categoria: "Cursos", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "Curso: Inglês Completo", preco: 159.90, emoji: "🌍", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_qcfwk6qcfwk6qcfw.png?auto=format&fit=crop&w=400&q=80", descricao: "Do iniciante ao avançado.", categoria: "Cursos", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "Curso: Espanhol para Negócios", preco: 139.90, emoji: "🌎", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_bxnf3jbxnf3jbxnf.png?auto=format&fit=crop&w=400&q=80", descricao: "Espanhol profissional.", categoria: "Cursos", status: "disponivel", pagamento: ["pix"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
  { nome: "Curso: UI/UX Design", preco: 169.90, emoji: "🎨", emojiUrl: "", imagem: "https://6970316076634d918b8775d4.imgix.net/Gemini_Generated_Image_wig59qwig59qwig5.png?auto=format&fit=crop&w=400&q=80", descricao: "Design de interfaces moderno.", categoria: "Cursos", status: "disponivel", pagamento: ["pix", "cartao"], checkout: { storeId: '$drip_duke', checkoutUrl: 'https://checkout.infinitepay.io/drip_duke/CGO5dGsV3' } },
];

module.exports = {
  SOFTWARE,
  EBOOKS,
  CURSOS,
  ALL_PRODUCTS: [...SOFTWARE, ...EBOOKS, ...CURSOS],
};
